advanced_flask homework done
oleksii-manzik/common pull request #12
Opened 2019-11-05 08:04 UTC by oleksii-manzik

2019-11-09 17:25 UTC, dimigor requested changes

2019-11-09 17:25 UTC, dimigor commented on flask3/products_blueprint/main.py
> +    data = get_data('products_blueprint/product_data.json')
you have constant for this path

2019-11-09 17:25 UTC, dimigor commented on flask3/utils.py
> +        return []
return empty dict, not list

2019-11-09 17:25 UTC, dimigor commented on flask3/utils.py
> +        with open(json_file, 'r') as file:
`file` is reserved python word, name variables better

2019-11-10 18:50 UTC, oleksii-manzik commented on flask3/products_blueprint/main.py
> +    data = get_data('products_blueprint/product_data.json')
fixed

2019-11-11 08:34 UTC, dimigor approved these changes

2019-11-11 08:34 UTC, dimigor commented on flask3/products_blueprint/templates/product.html
> +<h1>{{ product_data.name }}</h1>
tabulation

2019-11-13 20:58 UTC, merged