Flask5 homework
oleksii-manzik/common pull request #14
Opened 2019-11-20 21:47 UTC by oleksii-manzik

2019-12-03 16:07 UTC, dimigor requested changes

2019-12-03 16:07 UTC, dimigor commented on flask5/hotel/fields_check.py
> +from flask_restful import abort
name file like `..._util.py`

2019-12-03 16:07 UTC, dimigor commented on flask5/hotel/fields_check.py
> +        abort(400, error_code=400,
do not use here flask functions, just return message. Where you call these functions you check if message then abort

2019-12-03 16:07 UTC, dimigor commented on flask5/hotel/resources.py
> +        return f'New room {args["number"]} was successfully added'
return all room fields.
client should know what room with what fields was created

2019-12-03 16:07 UTC, dimigor commented on flask5/hotel/resources.py
> +        return f'Room {args["number"]} was successfully updated'
as above

2019-12-03 16:07 UTC, dimigor commented on flask_lesson_2/app.py
> +    print(data)
delete print

2019-12-08 12:57 UTC, oleksii-manzik commented on flask_lesson_2/app.py
> +    print(data)
it is not my print. hehe :)

2019-12-11 14:26 UTC, dimigor commented on flask4/hotel/db_utils.py
> +            f'''SELECT * FROM {left_letters_and_numbers_only(table)}
wow, what is ^M?

2019-12-11 14:26 UTC, dimigor commented on flask4/hotel/fields_check.py
> +        abort(400, error_code=400,
do not abort here, return only message, abort shoud be in views

2019-12-11 14:39 UTC, dimigor submitted a review, later dismissed

2019-12-26 14:19 UTC, merged