Tests practice homework
oleksii-manzik/common pull request #8
Opened 2019-10-07 11:06 UTC by oleksii-manzik

2019-10-12 15:52 UTC, dimigor commented on tests_practice/homework.py
> +    return list(set(list1).union(set(list2)))
please documenting your code and name your functions like what they do

2019-10-13 15:00 UTC, oleksii-manzik commented on tests_practice/homework.py
> +    return list(set(list1).union(set(list2)))
fixed

2019-10-14 21:49 UTC, yuriimchg requested changes
привіт, перевірив дз
загалом все ок, але потрібно виправити 1 завдання

також плюс за параметризацію пайтестів) 
юніттести не вийде параметризувати так само, але тесткейси можна загнати в список, поітерувати по них і підставити асерти (+ використати subtest)

на майбутнє: PEP-8 обмежує довжину рядка докстрінги до 72 символів:
https://www.python.org/dev/peps/pep-0008/#maximum-line-length

+ не забувай про type hints :wink:

2019-10-14 21:49 UTC, yuriimchg commented on tests_practice/homework.py
> +    return math.log(num, 3).is_integer() if num > 0 else False
дуже круте рішення

2019-10-14 21:49 UTC, yuriimchg commented on tests_practice/unittest_tests.py
> +from .homework import (common_between_two_lists,
старайся не використовувати відносні імпорти - вони працюють лише, якщо модуль, який їх має, імпортується в основний модуль

2019-10-14 21:49 UTC, yuriimchg commented on tests_practice/homework.py
> +    return list(set(list1).union(set(list2)))
цей метод має повертати переріз елементів двох списків, а не об'єднання

2019-10-15 06:52 UTC, oleksii-manzik commented on tests_practice/homework.py
> +    return list(set(list1).union(set(list2)))
@yuriimchg fixed

2019-10-15 06:53 UTC, oleksii-manzik commented on tests_practice/unittest_tests.py
> +from .homework import (common_between_two_lists,
@yuriimchg fixed

2019-10-15 06:53 UTC, oleksii-manzik commented on tests_practice/homework.py
> +    return list(set(list1).union(set(list2)))
@yuriimchg fixed

2019-10-15 18:01 UTC, yuriimchg reviewed
привіт
з дз все в порядку
але для того, щоб змерджити пул реквест, потрібно, щоб в ньому не було домашнього з тестами.
Створи, будь ласка, для нього окрему гілку і закинь його туди.

Лінк на інструкцію, як можна прибрати зайві файлики з цього ПР: http://www.codeblocq.com/2016/01/Untrack-files-already-added-to-git-repository-based-on-gitignore/

2019-10-15 18:01 UTC, yuriimchg commented on oop/homework.py
> +      if saturation_level eq 0 return text like this: "Your cat is dead :("
боюсь, тести захардкоджені на цю помилку :sweat_smile:

2019-10-16 06:22 UTC, oleksii-manzik commented on oop/homework.py
> +      if saturation_level eq 0 return text like this: "Your cat is dead :("
@yuriimchg це домашка по tests practice. я поправив, щоб там не було домашки по ооп

2019-10-16 07:25 UTC, dimigor approved these changes

2019-10-16 07:33 UTC, merged